# Generated by Django 5.2.17 on 2026-09-21 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='место проведения')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('stage', models.CharField(choices=[('submission', 'Приём заявок'), ('review', 'Рецензирование'), ('registration', 'Регистрация'), ('ongoing', 'Проведение'), ('finished', 'Завершена')], default='submission', max_length=20, verbose_name='этап')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'конференция',
                'verbose_name_plural': 'конференции',
                'ordering': ['-start_date'],
                'permissions': [('manage_stage', 'Может переводить конференцию на следующий этап'), ('revert_stage', 'Может возвращать конференцию на предыдущий этап')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='conference_end_not_before_start')],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('submission', 'Приём заявок'), ('review', 'Рецензирование'), ('registration', 'Регистрация'), ('ongoing', 'Проведение'), ('finished', 'Завершена')], max_length=20, verbose_name='с этапа')),
                ('to_stage', models.CharField(choices=[('submission', 'Приём заявок'), ('review', 'Рецензирование'), ('registration', 'Регистрация'), ('ongoing', 'Проведение'), ('finished', 'Завершена')], max_length=20, verbose_name='на этап')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто изменил')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='conferences.conference', verbose_name='конференция')),
            ],
            options={
                'verbose_name': 'переход между этапами',
                'verbose_name_plural': 'переходы между этапами',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['conference', '-created_at'], name='conferences_confere_e2e200_idx')],
            },
        ),
    ]
