# Generated by Django 5.2.17 on 2026-09-21 08:21

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=255, verbose_name='организация')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='страна')),
                ('orcid', models.CharField(blank=True, max_length=19, validators=[accounts.models.validate_orcid], verbose_name='ORCID')),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='идентификатор в старой системе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
