# Generated by Django 5.2.17 on 2026-09-21 08:22

import django.core.validators
import django.db.models.deletion
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_backfill_profiles'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='зарегистрирован')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference', verbose_name='конференция')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.profile', verbose_name='участник')),
            ],
            options={
                'verbose_name': 'регистрация',
                'verbose_name_plural': 'регистрации',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('conference', 'participant'), name='unique_registration_per_conference')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('abstract', models.TextField(verbose_name='аннотация')),
                ('file', models.FileField(blank=True, upload_to=submissions.models.submission_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), submissions.models.validate_file_size], verbose_name='файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.profile', verbose_name='автор')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.conference', verbose_name='конференция')),
            ],
            options={
                'verbose_name': 'заявка на доклад',
                'verbose_name_plural': 'заявки на доклады',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conference', 'status'], name='submissions_confere_2bd225_idx'), models.Index(fields=['author'], name='submissions_author__272c77_idx')],
            },
        ),
    ]
