# Generated by Django 5.2.17 on 2026-09-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'permissions': [('decide_submission', 'Может принимать и отклонять заявки')], 'verbose_name': 'заявка на доклад', 'verbose_name_plural': 'заявки на доклады'},
        ),
    ]
