# Generated by Django 5.2.17 on 2026-09-21 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='оценка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='назначена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='рецензент')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'рецензия',
                'verbose_name_plural': 'рецензии',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'reviewer'), name='unique_review_per_reviewer'), models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 1), ('score__lte', 5)), _connector='OR'), name='review_score_between_1_and_5')],
            },
        ),
    ]
