# Generated by Django 5.2.17 on 2026-09-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'permissions': [('assign_reviewer', 'Может назначать рецензентов на заявки')], 'verbose_name': 'рецензия', 'verbose_name_plural': 'рецензии'},
        ),
    ]
